backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "static/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "images/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "case-studies"
    label: "Case Study"
    folder: "content/case-studies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Custom Header Image", name: "custom_header_img", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Date", name: "showdate", widget: "boolean", default: "true"}
      
  - name: "press"
    label: "Press"
    folder: "content/press"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Original Publication", name: "original_publication", widget: "string", required: false}
      - {label: "Original URL", name: "original_article_url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Custom Header Image", name: "custom_header_img", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Date", name: "showdate", widget: "boolean", default: "true"}
