backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "static/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "images/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "case-studies"
    label: "Case Studies"
    folder: "content/news/case-studies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Show Date", name: "showdate", widget: "hidden", default: false}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Custom Header Image", name: "custom_header_img", widget: "string", required: false}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "case-study"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "case-study"}
      - label: "Client"
        name: "client"
        widget: "object"
        fields:
          - {label: "Client Name", name: "client_name", widget: "string"}
          - {label: "Client Description", name: "client_description", widget: "string"}
          - {label: "Client Logo", name: "partner_logo", widget: "string"}
          - {label: "Challenge", name: "challenge", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Quote"
        name: "quote"
        widget: object
        required: false
        fields:
          - {label: "Quote", name: "quote", widget: "text"}
          - {label: "Quotee", name: "quotee", widget: "string"}

  - name: "posts"
    label: "Blog Posts"
    folder: "content/news/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Original Publication", name: "original_publication", widget: "string", required: false}
      - {label: "Original URL", name: "original_article_url", widget: "string", required: false}
      - {label: "Custom Header Image", name: "custom_header_img", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Date", name: "showdate", widget: "boolean", default: true}
      - {label: "Show Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}

  - name: "support_pages"
    label: "Support Pages"
    files:
      - file: "content/support/administrator-support.md"
        label: "Administrator Support"
        name: "administrator-support"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "hidden", default: "support"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "faq"}
          - {label: "Page", name: "page", widget: "hidden", default: "/support/administrator-support.html"}
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "text"}
      - file: "content/support/renter-support.md"
        label: "Renter Support"
        name: "renter-support"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "hidden", default: "support"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "faq"}
          - {label: "Page", name: "page", widget: "hidden", default: "/support/renter-support.html"}
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "text"}

  - name: "top_level_pages"
    label: "Top Level Pages"
    files:
      - file: "content/about-facilitron.md"
        label: "About Facilitron"
        name: "about-facilitron"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
          - {label: "Page", name: "page", widget: "hidden", default: "/about-facilitron.html"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Seo Description", name: "description", widget: "text"}
          - {label: "Type", name: "type", widget: "hidden", default: "about-facilitron"}
      - file: "content/privacy.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
          - {label: "Page", name: "page", widget: "hidden", default: "/privacy.html"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Seo Description", name: "description", widget: "text"}
          - {label: "Type", name: "type", widget: "hidden", default: "privacy"}
      - file: "content/terms.md"
        label: "Terms of Use"
        name: "terms-of-use"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
          - {label: "Page", name: "page", widget: "hidden", default: "/terms.html"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Seo Description", name: "description", widget: "text"}
          - {label: "Type", name: "type", widget: "hidden", default: "terms"}
      - file: "content/press-kit.md"
        label: "Press Kit"
        name: "press-kit"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
          - {label: "Page", name: "page", widget: "hidden", default: "/press-kit.html"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Seo Description", name: "description", widget: "text"}
          - {label: "Type", name: "type", widget: "hidden", default: "terms"}
