baseURL = "https://resolutionathens.github.io/facilitron-news/"
disqusShortname = "disqus_ygr6wmlEnU"
languageCode = "en-us"
theme = "facilitron"
title = "Facilitron News"
[[menu.main]]
name = "Home"
url = "/"
weight = -110
[params]
address = "485 Alberto Way, Suite 230, Los Gatos, CA 95032"
dateform = "January 2, 2006"
description = "The evolution of facility management"
email = "GetStarted@facilitron.com"
favicon = "images/gt_favicon.png"
name = "Facilitron"
phone = "800.272.2962"
year = 2017
[params.disqus]
site = "facilitron.disqus.com"
[params.google.analytics]
trackerid = "GA-000000000-0"
[params.sharethis]
custom = true
property = "5a07366950e8bc00116c801d"
[[params.social]]
footer = true
icon = "fa-facebook-square"
network = "facebook"
sharethis = true
title = "facebook"
url = "https://www.facebook.com/facilitron/"
[[params.social]]
footer = true
icon = "fa-twitter-square"
network = "twitter"
sharethis = true
title = "twitter"
url = "https://twitter.com/FacilitronInc"
[[params.social]]
footer = true
icon = "fa-instagram"
network = ""
sharethis = false
title = "instagram"
url = "https://www.instagram.com/facilitron/"
[[params.social]]
footer = false
icon = "fa-linkedin-square"
network = "linkedin"
sharethis = true
title = "linkedin"
url = "https://www.linkedin.com/company/facilitron"
[[params.social]]
footer = false
icon = "fa-envelope"
network = "email"
sharethis = true
title = "email"
url = "mailto:GetStarted@facilitron.com"
