baseURL = "https://facilitron.netlify.com/"
# disqusShortname = "disqus_ygr6wmlEnU"
languageCode = "en-us"
title = "Facility Management, Evolved"
[params]
address = "485 Alberto Way, Suite 230, Los Gatos, CA 95032"
dateform = "January 2, 2006"
description = "The evolution of facility management"
email = "GetStarted@facilitron.com"
favicon = "images/favicon.ico"
name = "Facilitron"
phone = "800.272.2962"
year = 2017
# [params.disqus]
# site = "facilitron.disqus.com"
[params.google.analytics]
trackerid = "UA-88933286-1"

[[menu.main]]
  name = "Overview"
  identifier = "platform"
  weight = -5

[[menu.main]]
  name = "District OS"
  identifier = "overview"
  url = "/platform-features/overview"
  parent = "platform"
  weight = 1

[[menu.main]]
  name = "Scheduling & Reservations"
  identifier = "scheduling"
  url = "/platform-features/scheduling"
  parent = "platform"
  weight = 5

[[menu.main]]
  name = "Work Management"
  identifier = "work-orders"
  url = "/platform-features/work-orders"
  parent = "platform"
  weight = 10

[[menu.main]]
  name = "Business Insights"
  identifier = "business-insights"
  url = "/platform-features/business-insights"
  parent = "platform"
  weight = 15

[[menu.main]]
  name = "Pricing"
  identifier = "pricing"
  url = "/platform-features/pricing"
  parent = "platform"
  weight = 20

[[menu.main]]
  name = "News"
  identifier = "news"
  url = "/news/"
  weight = 5

[[menu.main]]
  name = "Administrator Support"
  identifier = "administrator-support"
  url = "/support/administrator-support"
  parent = "Support"
  weight = 1

[[menu.main]]
  name = "Renter Support"
  identifier = "renter-support"
  url = "/support/renter-support"
  parent = "Support"
  weight = 5

[[menu.main]]
  name = "Contact Support"
  identifier = "contact-support"
  url = "/support/contact-support"
  parent = "Support"
  weight = 10

[[menu.main]]
  name = "Contact Sales"
  identifier = "contact-sales"
  url = "/support/contact-sales"
  parent = "Support"
  weight = 15
