baseURL = "https://facilitron.netlify.com/"
disqusShortname = "disqus_ygr6wmlEnU"
languageCode = "en-us"
title = "Facility Management, Evolved."
[params]
address = "485 Alberto Way, Suite 230, Los Gatos, CA 95032"
dateform = "January 2, 2006"
description = "The evolution of facility management"
email = "GetStarted@facilitron.com"
favicon = "images/favicon.ico"
name = "Facilitron"
phone = "800.272.2962"
year = 2017
[params.disqus]
site = "facilitron.disqus.com"
[params.google.analytics]
trackerid = "UA-88933286-1"
[[menu.main]]
  name = "FAQ"
  identifier = "faq"
  url = "/support/faq"
  parent = "Support"
  weight = -10
[[menu.main]]
  name = "Application Support"
  identifier = "application-support"
  url = "/support/application-support"
  parent = "Support"
[[menu.main]]
  name = "Platform Overview"
  identifier = "overview"
  url = "/overview/"
  weight = -10
[[menu.main]]
  name = "Case Studies"
  identifier = "case-studies"
  url = "/case-studies/"
  weight = 1
[[menu.main]]
  name = "News"
  identifier = "news"
  url = "/news/"
  weight = 5
