---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
  press:
    default_front_matter_template: fairfield-suisun-unified-school-district-plans-changes-in-facility-use-process
version: '0.28'
